version: '3.8'

services:
  node-app:
    container_name: node-app
    build: .
    networks:
      - belgsoftNetwork
    ports:
      - "80:3000"
    depends_on:
       mysql:
          condition: service_healthy

  mysql:
    container_name: mysqlDb
    build:
        context: .
        dockerfile: Dockerfile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=14923
    networks:
      - belgsoftNetwork
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 7s
      timeout: 5s
      retries: 3

networks:
    belgsoftNetwork:
        driver: bridge
