export enum AreaError {
    AREA_NOT_FOUND = 'AREA_NOT_FOUND',
    AREA_NOT_UPDATED = 'AREA_NOT_UPDATED',
    AREA_NOT_DELETED = 'AREA_NOT_DELETED',
    AREA_ERROR_CANNOT_GET_AREAS = 'AREA_ERROR_CANNOT_GET_AREAS',
    AREA_ERROR_CANNOT_CREATE_AREA = 'AREA_ERROR_CANNOT_CREATE_AREA',
    AREA_ERROR_CANNOT_UPDATE_AREA = 'AREA_ERROR_CANNOT_UPDATE_AREA',
    AREA_CANNOT_BE_DELETED_ERROR = 'AREA_CANNOT_BE_DELETED_ERROR'
}