export enum AreaErrors {
    AREA_NOT_FOUND = 'AREA_NOT_FOUND',
    AREA_NOT_UPDATED = 'AREA_NOT_UPDATED',
    AREA_CANNOT_BE_FOUND_ERROR = 'AREA_CANNOT_BE_FOUND_ERROR',
    AREA_ERROR_CANNOT_GET_AREAS = 'AREA_ERROR_CANNOT_GET_AREAS',
    AREA_ERROR_CANNOT_CREATE_AREA = 'AREA_ERROR_CANNOT_CREATE_AREA',
    AREA_ERROR_CANNOT_UPDATE_AREA = 'AREA_ERROR_CANNOT_UPDATE_AREA',
    AREA_ERROR_CANNOT_DELETE_AREA = 'AREA_ERROR_CANNOT_DELETE_AREA'
}