export const AUTH_ERRORS = {
    AUTH_ERROR_INCORRECT_PASSWORD: 'AUTH_ERROR_INCORRECT_PASSWORD',
    AUTH_ERROR_CANNOT_REGISTER_USER: 'AUTH_ERROR_CANNOT_REGISTER_USER',
    AUTH_ERROR_CANNOT_LOGIN_USER: 'AUTH_ERROR_CANNOT_LOGIN_USER',
    AUTH_ERROR_INVALID_SESSION: 'AUTH_ERROR_INVALID_SESSION',
    AUTH_ERROR_EMAIL_ALREADY_EXISTS: 'AUTH_ERROR_EMAIL_ALREADY_EXISTS',
}