export const AUTH_ERRORS = {
    AUTH_INCORRECT_PASSWORD: 'AUTH_INCORRECT_PASSWORD',
    AUTH_CANNOT_REGISTER_USER: 'AUTH_CANNOT_REGISTER_USER',
    AUTH_CANNOT_LOGIN_USER: 'ERROR_LOGIN_USER',
    AUTH_INVALID_SESSION: 'AUTH_INVALID_SESSION',
    AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
}