export enum MenuError {
    MENU_NOT_FOUND = "MENU_NOT_FOUND",
    MENU_NOT_DELETED = "MENU_NOT_DELETED",
    MENU_NOT_UPDATED = "MENU_NOT_UPDATED",
    MENUS_CANNOT_BE_FOUND_ERROR = "MENUS_CANNOT_BE_FOUND_ERROR",
    MENU_ERROR_CANNOT_CREATE_MENU = "MENU_ERROR_CANNOT_CREATE_MENU",
    MENU_ERROR_CANNOT_UPDATE_MENU = "MENU_ERROR_CANNOT_UPDATE_MENU",
    MENU_ERROR_CANNOT_DELETE_MENU = "MENU_ERROR_CANNOT_DELETE_MENU",
}