export const MenuErrors = {
    MENU_NOT_FOUND: "MENU_NOT_FOUND",
    MENU_ERROR_CANNOT_GET_MENUS: "MENU_ERROR_CANNOT_GET_MENUS",
    MENU_ERROR_CANNOT_CREATE_MENU: "MENU_ERROR_CANNOT_CREATE_MENU",
    MENU_ERROR_CANNOT_UPDATE_MENU: "MENU_ERROR_CANNOT_UPDATE_MENU",
    MENU_ERROR_CANNOT_DELETE_MENU: "MENU_ERROR_CANNOT_DELETE_MENU",
}