export const OrderErrors = {
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    ORDER_ERROR_CANNOT_CREATE_ORDER: 'ORDER_ERROR_CANNOT_CREATE_ORDER',
    ORDER_ERROR_CANNOT_UPDATE_ORDER: 'ORDER_ERROR_CANNOT_UPDATE_ORDER',
    ORDER_ERROR_CANNOT_DELETE_ORDER: 'ORDER_ERROR_CANNOT_DELETE_ORDER',
    ORDER_ERROR_CANNOT_GET_ORDERS: 'ORDER_ERROR_CANNOT_GET_ORDERS',
}