export enum RoleError {
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
    ROLE_ERROR_CANNOT_CREATE_ROLE = "ROLE_ERROR_CANNOT_CREATE_ROLE",
    ROLE_ERROR_CANNOT_UPDATE_ROLE = "ROLE_ERROR_CANNOT_UPDATE_ROLE",
    ROLE_ERROR_CANNOT_DELETE_ROLE = "ROLE_ERROR_CANNOT_DELETE_ROLE",
    ROLE_ERROR_CANNOT_GET_ROLES = "ROLE_ERROR_CANNOT_GET_ROLES",
    ROLE_ERROR_CANNOT_GET_ROLE = "ROLE_ERROR_CANNOT_GET_ROLE",
    ROLE_NOT_UPDATED = "ROLE_NOT_UPDATED",
}