export const TABLE_ERRORS = {
    TABLE_ERROR_CANNOT_GET_TABLES: "ERROR_CANNOT_GET_TABLES",
    TABLE_ERROR_CANNOT_CREATE_TABLE: "TABLE_ERROR_CANNOT_CREATE_TABLE",
    TABLE_ERROR_CANNOT_UPDATE_TABLE: "TABLE_ERROR_CANNOT_UPDATE_TABLE",
    TABLE_ERROR_CANNOT_DELETE_TABLE: "TABLE_ERROR_CANNOT_DELETE_TABLE",
    TABLE_ERROR_CANNOT_GET_TABLE: "ERROR_CANNOT_GET_TABLE",
    TABLE_ERROR_TABLE_ALREADY_EXISTS: "TABLE_ERROR_TABLE_ALREADY_EXISTS",
    TABLE_ERROR_TABLE_DOES_NOT_EXIST: "TABLE_ERROR_TABLE_DOES_NOT_EXIST",
}