export const TableErrors = {
    TABLE_ERROR_CANNOT_GET_TABLES: "ERROR_CANNOT_GET_TABLES",
    TABLE_ERROR_CANNOT_CREATE_TABLE: "TABLE_ERROR_CANNOT_CREATE_TABLE",
    TABLE_ERROR_CANNOT_UPDATE_TABLE: "TABLE_ERROR_CANNOT_UPDATE_TABLE",
    TABLE_ERROR_CANNOT_DELETE_TABLE: "TABLE_ERROR_CANNOT_DELETE_TABLE",
    TABLE_ERROR_CANNOT_GET_TABLE: "ERROR_CANNOT_GET_TABLE",
    TABLE_ERROR_TABLE_ALREADY_EXISTS: "TABLE_ERROR_TABLE_ALREADY_EXISTS",
    TABLE_ERROR_TABLE_NOT_FOUND: "TABLE_ERROR_TABLE_NOT_FOUND",
}