export const TABLE_ERRORS = {
    ERROR_CANNOT_GET_TABLES: "ERROR_CANNOT_GET_TABLES",
    ERROR_CANNOT_CREATE_TABLE: "ERROR_CANNOT_CREATE_TABLE",
    ERROR_CANNOT_UPDATE_TABLE: "ERROR_CANNOT_UPDATE_TABLE",
    ERROR_CANNOT_DELETE_TABLE: "ERROR_CANNOT_DELETE_TABLE",
    ERROR_CANNOT_GET_TABLE: "ERROR_CANNOT_GET_TABLE",
}