export enum UserError {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_NOT_UPDATED = 'USER_NOT_UPDATED',
    USER_ERROR_CANNOT_GET_USER = 'USER_ERROR_CANNOT_GET_USER',
    USER_ERROR_CANNOT_GET_USERS = 'USER_ERROR_CANNOT_GET_USERS',
    USER_ERROR_CANNOT_CREATE_USER = 'USER_ERROR_CANNOT_CREATE_USER',
    USER_ERROR_CANNOT_UPDATE_USER = 'USER_ERROR_CANNOT_UPDATE_USER',
}