
export enum UserStateError {
    USER_STATE_NOT_FOUND = 'USER_STATE_NOT_FOUND',
    USER_STATE_ERROR_CANNOT_CREATE_USER_STATE = 'USER_STATE_ERROR_CANNOT_CREATE_USER_STATE',
    USER_STATE_ERROR_CANNOT_UPDATE_USER_STATE = 'USER_STATE_ERROR_CANNOT_UPDATE_USER_STATE',
    USER_STATE_ERROR_CANNOT_DELETE_USER_STATE = 'USER_STATE_ERROR_CANNOT_DELETE_USER_STATE',
    USER_STATE_ERROR_CANNOT_GET_USER_STATES = 'USER_STATE_ERROR_CANNOT_GET_USER_STATES',
}
