export const USER_ERRORS = {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
    ERROR_REGISTER_USER: 'ERROR_REGISTER_USER',
    ERROR_LOGIN_USER: 'ERROR_LOGIN_USER',
}